project:
  type: website
  output-dir: docs

website:
  title: "Iowa Liquor Sales: 2.0+1.0 You are (Not) in a Pandemic"

format:
  html:
    theme:
      light:
      - cosmo
      - light.scss
      dark:
      - slate
      - dark.scss
